### ISSUE TITLE
POs, Direct, others work on SUL policies on library data in the cloud

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/taco-truck#16]
Target directors' office for moving conversation forward on cloud storage & policy statements on risk mitigation for this wrt library data. Possible partnership with Preservation Team on this. TBD what documentation we need to generation to aid those conversations.

**Comment by cmh2166** [comment]
@julianmorley have you worked on this in some capacity already wrt preservation or just Ops work?

**Comment by cmh2166** [comment]
Get meeting together with Direct on how to get this missing.

**Comment by hannahfrost** [comment]
@cmh2166 I scheduled a meeting on May 16 for a subset of the SDR team and Direct (it's on your calendar) to discuss this issue. In advance, I will ask curatorial stakeholders to provide any examples of collection agreements (deeds of gift, purchase agreements and the like) that forbid storage "beyond Stanford"

**Comment by cmh2166** [comment]
I saw - perfect, and thank you!
		
		

		Get Outlook for iOS
	




On Mon, Apr 9, 2018 at 4:40 PM -0700, "hannahfrost" <notifications@github.com> wrote:












@cmh2166 I scheduled a meeting on May 16 for a subset of the SDR team and Direct (it's on your calendar) to discuss this issue. In advance, I will ask curatorial stakeholders to provide any examples of collection agreements (deeds of gift, purchase agreements and the like) that forbid storage "beyond Stanford"
